name: MyLocalSearch Cypress Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install google-chrome-stable

      - name: Run Cypress tests
        run: npm run test:ci

      - name: Upload test reports
        uses: actions/upload-artifact@v2
        if: always()  # Upload reports even if tests fail
        with:
          name: cypress-reports
          path: cypress/reports
          retention-days: 30

      - name: Upload screenshots of failed tests
        uses: actions/upload-artifact@v2
        if: failure()  # Only upload on test failure
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 30 